apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wezvaspringbootapp-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: wezvaspringbootapp
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20 
